### ISSUE TITLE
Cookies.GetAll fails

### ISSUE THREAD

**Issue by radiolondra** [mingyaulee/WebExtensions.Net#17]
I am not sure it is an error in the library, rather I am more inclined to think it is my mistake.

I am trying to use the `WebExtensions.Cookies.GetAll()` function to show all browser cookies in a table from a page content. I had previously used `IJSRuntime` and a JavaScript function to reach the same result and everything worked fine.
Instead with WebExtensions I have the following result:

![weerror](https://user-images.githubusercontent.com/20070559/204134221-a958d1e2-9cab-4492-99ef-f4cbb199aac9.png)

This is the function I use to get the cookies:
```
....
private static IEnumerable<WebExtensions.Net.Cookies.Cookie> cookiesWE { get; set; } = new List<WebExtensions.Net.Cookies.Cookie>();
....
private async Task GetAllBrowserCookiesWE()
{        
    WebExtensions.Net.Cookies.GetAllDetails details = new();       
    cookiesWE = await WebExtensions.Cookies.GetAll(details); <<---- the error is here
   .....
}
```

Below is the complete error:

```
JsBindNet.js:888 
Error: Target object is null or undefined.
    at JsBindNet._invokeFunctionInternal (JsBindNet.js:957:15)
    at JsBindNet.InvokeFunctionAsync (JsBindNet.js:877:32)
    at blazor.webassembly.js:1:3337
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (blazor.webassembly.js:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (blazor.webassembly.js:1:62747)
    at Object.mono_wasm_invoke_js_blazor (dotnet.7.0.0.e2k3i44qrp.js:5983:44)
    at _mono_wasm_invoke_js_blazor (dotnet.7.0.0.e2k3i44qrp.js:9832:103886)
    at dotnet.wasm:0x1d4a3
    at dotnet.wasm:0x1c8d1
InvokeFunctionAsync @ JsBindNet.js:888

blazor.webassembly.js:1 
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Target object is null or undefined.
JsBind.Net.JsBindException: Target object is null or undefined.
Error: Target object is null or undefined.
    at JsBindNet._invokeFunctionInternal (chrome-extension://ipndphdmjfmdigabfnonchhomjcjkana/content/JsBind.Net/JsBindNet.js:957:15)
    at JsBindNet.InvokeFunctionAsync (chrome-extension://ipndphdmjfmdigabfnonchhomjcjkana/content/JsBind.Net/JsBindNet.js:877:32)
    at chrome-extension://ipndphdmjfmdigabfnonchhomjcjkana/framework/blazor.webassembly.js:1:3337
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (chrome-extension://ipndphdmjfmdigabfnonchhomjcjkana/framework/blazor.webassembly.js:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (chrome-extension://ipndphdmjfmdigabfnonchhomjcjkana/framework/blazor.webassembly.js:1:62747)
    at Object.mono_wasm_invoke_js_blazor (chrome-extension://ipndphdmjfmdigabfnonchhomjcjkana/framework/dotnet.7.0.0.e2k3i44qrp.js:5983:44)
    at _mono_wasm_invoke_js_blazor (chrome-extension://ipndphdmjfmdigabfnonchhomjcjkana/framework/dotnet.7.0.0.e2k3i44qrp.js:9832:103886)
    at chrome-extension://ipndphdmjfmdigabfnonchhomjcjkana/framework/dotnet.wasm:wasm-function[313]:0x1d4a3
    at chrome-extension://ipndphdmjfmdigabfnonchhomjcjkana/framework/dotnet.wasm:wasm-function[283]:0x1c8d1

DotNet stack trace: 
   at JsBind.Net.JsRuntimeAdapter.<InvokeAsyncInternal>d__14`1[[System.Collections.Generic.IEnumerable`1[[WebExtensions.Net.Cookies.Cookie, WebExtensions.Net, Version=0.12.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at JsBind.Net.JsRuntimeAdapter.<InvokeAsync>d__9`1[[System.Collections.Generic.IEnumerable`1[[WebExtensions.Net.Cookies.Cookie, WebExtensions.Net, Version=0.12.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at CookieExtension.Pages.ContentScript.GetAllBrowserCookiesWE() in 
C:\Users\Robi\Documents\ALL-VS-PROJECTS\Projects VS 2022\CookieExtension\CookieExtension\Pages\ContentScript.razor:line 163
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at BlazorStrap.BlazorStrapActionBase.ClickEvent(MouseEventArgs e)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
Where am I going wrong?

**Comment by mingyaulee** [comment]
One thing that I can immediately think of is maybe the [`cookies` permission](https://developer.chrome.com/docs/extensions/reference/cookies/#manifest) hasn't been declared in the manifest?

**Comment by radiolondra** [comment]
no, it is declared in manifest. As I said it worked with IJSRuntime and Javascript.
Anyway this is the manifest:

```
{
  "manifest_version": 3,
  "name": "Cookie Extension",
  "description": "My browser extension built with Blazor WebAssembly",
  "version": "0.2",

  "action": {
    "default_popup": "popup.html"
  },

  "options_ui": {
    "page": "options.html",
    "open_in_tab": true
  },

  "background": {
    "service_worker": "BackgroundWorker.js",
    "type": "module"
  },

  
  "content_scripts": [
    {
      "matches": [ "*://*/*" ],
      //"match_origin_as_fallback": true,
      //    "js": [
      //      "content/Blazor.BrowserExtension/ContentScript.js"
      //    ],
      "js": [
        "content/BlazorStrap/popper.min.js",
        "content/BlazorStrap/blazorstrap.js",
        "js/ScriptContent.js"
      ],
      "css": [
        "CookieExtension.styles.css",
        "css/bootstrap/bootstrap.min.css"
      ]
    }
  ],

  "content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; object-src 'self';",
    "sandbox": "sandbox allow-scripts; script-src 'self'; object-src 'self'"
  },

  "permissions": [ "scripting", "storage", "unlimitedStorage", "tabs", "webRequest", "cookies", "nativeMessaging", "activeTab" ],

  "optional_permissions": [],

  "host_permissions": [
    "*://*/*"
  ],

  "web_accessible_resources": [
    {
      "resources": [
        "framework/*",
        "content/*",
        "app.js"
      ],
      "matches": [ "<all_urls>" ]
    }
  ]
}
```

**Comment by mingyaulee** [comment]
I have tested it myself, assuming that you are using the API in the content scripts, it doesn't work there. The API is not accessible from the content scripts and will have to communicate with the service worker to get the data. Here is a [list of all the APIs available](https://developer.chrome.com/docs/extensions/mv3/content_scripts/) in the content scripts.

**Comment by radiolondra** [comment]
I figured as much. In fact, in my IJSRuntime version I called a function in the content script that in turn sent the request to the background worker via sendMessage.

**in ContentScript.razor**
```
private async Task GetAllBrowserCookies()
{ 
    await js.InvokeVoidAsync("getAllCookiesMessage");        
}
```

**in ScriptContent.js**
```
var getAllCookiesMessage = async function () {
    var cookies;
    await chrome.runtime.sendMessage({ action: "getAllCookies" })   
    .then(response => {
        cookies = response;
    });
    DotNet.invokeMethodAsync("CookieExtension", "ShowAllActiveCookies", cookies);
}
```

**in BackgroundWorker.js**

```
browser.runtime.onMessage.addListener(
    function (message, sender, sendResponse) {
        switch (message.action) {
            case "openDialog":
                sendResponse('Hello from content');
                break;
            case "getActiveTab":
                var id = getActiveTab();
                sendResponse(id);                
            case "getAllCookies":
                sendResponse(getAllCookies());
                break;
        }
        return true;
    }
);

var getAllCookies = async function () {
    var cookieArray = [];
    var count = 0;
    await browser.cookies
        .getAll({})
        .then(cookies => {
            count = cookies.length;
            //alert(cookies.length);
            cookies.forEach(function (cookie) {
                cookieArray.push({
                    name: cookie.name,
                    domain: cookie.domain,
                    value: cookie.value,
                    path: cookie.path
                });
            });
            
        });
    return JSON.stringify(cookieArray);
}
```

I'll try to do the same using WebExtensions.

I wonder if it is possible to create a background worker using WebExtensions, but I highly doubt it since moreover it has to be declared in the manifest.
