### ISSUE TITLE
browser.runtime.sendMessage Fail

### ISSUE THREAD

**Issue by zzc1231** [mingyaulee/WebExtensions.Net#18]
browser-polyfill.js:1171 
        
       Uncaught Error: Expected at most 3 arguments for sendMessage(), got 4
    at o (browser-polyfill.js:1171:15)
    at Object.apply (browser-polyfill.js:872:26)
    at content-script.js:11:25
    
```js
  var intervalID = setInterval(() => {
        console.log("即将获取token")

        const token = localStorage.getItem("token");
        console.log(token);

        //https://developer.chrome.com/docs/extensions/reference/runtime/#method-sendMessage
        browser.runtime.sendMessage(
            browser.runtime.id,
            token,
            {},
            () => {
                console.log("收到响应");
                clearInterval(intervalID);
            });
    }, 3000)
```

**Comment by mingyaulee** [comment]
The `browser-polyfill` is provided by Mozilla for cross browser compatibility, and it converts all calls with callbacks to JS promise. Instead of providing the callback as the last parameter, change it to `await browser.runtime.sendMessage(..., ..., ...)`
